### ISSUE TITLE
UI Design for Circle Page

### ISSUE THREAD

**Issue by EashanKaushik** [gcivil-nyu-org/S2022-Team-6-repo#10]

**Comment by EashanKaushik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-6-Workspace-6207e87cf02ddd0011d5836b/issues/gcivil-nyu-org/S2022-Team-6-repo/10?planning-poker) with ZenHub @pranavsinghps1 @chinmaykulkarni95 @srijanmalhotra2711 @Shardhakoul

**Comment by Shardhakoul** [comment]
3

**Comment by srijanmalhotra2711** [comment]
Checked and Approved.
