### ISSUE TITLE
Testing Party Bug: Main bar buttons not working on profile page.

### ISSUE THREAD

**Issue by Pruthviraj98** [gcivil-nyu-org/S2022-Team-6-repo#203]
The buttons on the main bar (on top of the screen) wont work (which should be redirected to the particular section in the homepage) when I am on the the Profile page. 

NOTE: **But they work just fine on home page.**

![Screen Shot 2022-04-17 at 3.11.21 PM.png](https://images.zenhubusercontent.com/6204657c5153f31dc249bc95/d23656dd-43f0-43dd-b545-38259559e584)

**Comment by srijanmalhotra2711** [comment]
Thanks for pointing this out but I guess we have mentioned in the document that this specific page doesn't have a functioning nav bar.
