### ISSUE TITLE
Testing Party Bug ( Email field is not validated on Signup Page)

### ISSUE THREAD

**Issue by manektamanna** [gcivil-nyu-org/S2022-Team-6-repo#204]
If a user enters an invalid email address while signing up for your application, it gets accepted and the application creates an account for that user.

![Screenshot (408)](https://user-images.githubusercontent.com/85683392/163732570-677f2c32-783d-430c-8421-951deceab897.png)

**Comment by srijanmalhotra2711** [comment]
This issue is a duplicate. 
It has been resolved.
