### ISSUE TITLE
Testing Party Bug (Error in Monitor page)

### ISSUE THREAD

**Issue by manektamanna** [gcivil-nyu-org/S2022-Team-6-repo#205]
If a user tries to select from-date which is greater than to-date on the monitor page, it does not raise an error.

![Screenshot (409)](https://user-images.githubusercontent.com/85683392/163733029-d4cfef8a-fc57-47e4-b28c-529c3ab1dece.png)

**Comment by srijanmalhotra2711** [comment]
1. Thanks for pointing this out. Though as mentioned in the document this functionality is not working yet. Please check back in a few days to find the working functionality.
