### ISSUE TITLE
Testing Party Bug ( Settings Page)

### ISSUE THREAD

**Issue by manektamanna** [gcivil-nyu-org/S2022-Team-6-repo#206]
1. There are no validations on the Setting page where the user is able to change their profile.
2.  It is taking the future date as the date of birth.
3. The phone no. field has no validation.

![Screenshot (410)](https://user-images.githubusercontent.com/85683392/163733328-65d156a8-5f9c-4518-bbf9-c12f95ce6af4.png)

**Comment by srijanmalhotra2711** [comment]
These issues have now been resolved. 
Please refer to the new update.
