### ISSUE TITLE
Testing Party

### ISSUE THREAD

**Issue by aaronk4311** [gcivil-nyu-org/S2022-Team-6-repo#207]
1. When I am logged in, it allows me to sign up for a new account if I have the signup link open in another tab/window. Once I signed up while logged in, it allows me to log into a separate account even though I was already logged in.

2. When I enter an invalid phone number, it accepts it and saves it on my profile.

3. If I'm on my profile, https://coviguard.herokuapp.com/settings/test5/profile, and I click on one of the links on the header, it doesn't bring me to the respective area on the homepage, but rather an invalid link, e.g., if I click Developers, it brings me to https://coviguard.herokuapp.com/settings/test5/profile#developers

4. When I click Edit Permission on test_circle5 (the circle that test5 account owns), it doesn't seem to let me edit anything.

5. When I leave a circle, it doesn't show up in the notifications (not the alerts functionality, which I did not test as requested) saying that I had left a circle.

**Comment by srijanmalhotra2711** [comment]
These issues have now been resolved. 
Please refer to the new update.
