### ISSUE TITLE
Testing Party Bugs

### ISSUE THREAD

**Issue by hazenoeasy** [gcivil-nyu-org/S2022-Team-6-repo#208]
The  Lasted update date is wrong
![Screen Shot 2022-04-17 at 7.40.51 PM.png](https://images.zenhubusercontent.com/62046570b897e985131ec7b3/19b4265a-f6a2-42fc-9762-ffe7cacda8cf)

**Comment by srijanmalhotra2711** [comment]
This issue has now been resolved. 
You should be able to see the updated date.
