### ISSUE TITLE
Testing Party bugs

### ISSUE THREAD

**Issue by furrkai** [gcivil-nyu-org/S2022-Team-6-repo#209]
<img width="666" alt="1650239723(1)" src="https://user-images.githubusercontent.com/83237232/163736860-4ecae4bf-1ca4-4736-ad56-e78ee6690a4d.png">
<img width="975" alt="1650239760(1)" src="https://user-images.githubusercontent.com/83237232/163736871-c94d9647-6925-4c34-974d-bbd805bf2202.png">

If I input a long circle name, it will redirect to a Django DataError page. It would be better to remind the user that the name is too long on the create circle form.

**Comment by srijanmalhotra2711** [comment]
This issue has now been resolved.
