### ISSUE TITLE
Testing Party Bugs

### ISSUE THREAD

**Issue by RIC06X** [gcivil-nyu-org/S2022-Team-6-repo#210]
1. bar chart does not update after changing dates
2. can see other users’ email when changing urls to other users name
    [https://coviguard.herokuapp.com/test2](https://coviguard.herokuapp.com/test2)
3. Cannot join self-created circle
4. Phone Number digits has no limitation
5. Upload photo size has no limitation

**Comment by srijanmalhotra2711** [comment]
1. Thanks for the input. As mentioned in the document this was not to be tested yet. Please check back soon for the working model. 
2. Could you please be a little specific?
3. You are already a part of the circle you created. Gives you an admin role.
4. and 5. Thanks for the update.

**Comment by srijanmalhotra2711** [comment]
These issues have now been resolved. 
Please refer to the new update.
