### ISSUE TITLE
Testing Party issues

### ISSUE THREAD

**Issue by pb2640** [gcivil-nyu-org/S2022-Team-6-repo#211]
-  On Sign in Page, user can sign up using bogus inputs as seen in the screenshot below. This form can be validated.

![image](https://user-images.githubusercontent.com/90818379/163745776-07a27234-ad8c-4132-a46f-3c1bc52d388b.png)

- The chart does not update on updating the dates

![image](https://user-images.githubusercontent.com/90818379/163746052-986292bf-560f-49f3-ad9d-0a5d3e69dd35.png)

-

**Comment by srijanmalhotra2711** [comment]
These issues have now been resolved. 
Please refer to the new update.
