### ISSUE TITLE
Testing Party: Signup validation

### ISSUE THREAD

**Issue by abirbhav** [gcivil-nyu-org/S2022-Team-6-repo#212]
I was able to signup using a username of a, an email of a@a.com and password 'a'. Consider adding email verification and password validation.

![image](https://user-images.githubusercontent.com/13178956/163746300-d6de8004-c15c-4ad2-b85b-be851ebe13f3.png)

**Comment by srijanmalhotra2711** [comment]
This issue has now been resolved. 
Please refer to the new update.
