### ISSUE TITLE
Testing party

### ISSUE THREAD

**Issue by nevermoreno1** [gcivil-nyu-org/S2022-Team-6-repo#215]
when I just created a circle, but it showed last updated three days ago. Also for notifications system, when I clicked it away and refreshed, it still pop up.
<img width="1384" alt="Screen Shot 2022-04-18 at 5 14 41 PM" src="https://user-images.githubusercontent.com/51802554/163879685-ca4a1ab7-8a47-4e72-bf6f-993ab2bd01a6.png">

**Comment by srijanmalhotra2711** [comment]
This issue is a duplicate. 
It has been resolved.
