### ISSUE TITLE
Testing Party

### ISSUE THREAD

**Issue by Shravanirakshe** [gcivil-nyu-org/S2022-Team-6-repo#219]
1. After changing Cities from New York City -> Saratoga -> New York City, the line graph appears to be straight from the month of January.
<img width="1434" alt="Screen Shot 2022-04-18 at 10 21 20 PM" src="https://user-images.githubusercontent.com/53651879/163907701-d46e6d95-473b-474a-a7f6-e9302281eb88.png">

**Comment by srijanmalhotra2711** [comment]
Thanks for pointing it out. 
Though this was mentioned under what is not functioning. Requesting you to try it out soon as we will be rectifying it.

**Comment by srijanmalhotra2711** [comment]
This has been resolved.
