### ISSUE TITLE
Create Circle

### ISSUE THREAD

**Issue by EashanKaushik** [gcivil-nyu-org/S2022-Team-6-repo#29]
**User Story**
* As a user, I want to create circles so that I can add other users to them.
* As a circle admin, I want to attach specific policies to my circle so that it satisfies the circle objective.
* As a user, I should be able to accept or decline circle policies so that I don't share sensitive information with someone I don't want to. 

**Acceptance Criteria**
Registered users should be able to create new Circles, and attach certain policies to these circles. Tentative UI for this functionality.

**Comment by Shardhakoul** [comment]
Checked and Approved.
