### ISSUE TITLE
As developer, I want set up a database for the product so that users information and circle information can be saved in the DB.

### ISSUE THREAD

**Issue by EashanKaushik** [gcivil-nyu-org/S2022-Team-6-repo#65]
**User story**

- As a developer, I want to select a database that can handle real-time data updates. 

**Acceptance criteria**
The database should be set up and integrated into the application using Django. Selected DB should be able to handle large data such as historical covid data.

**Comment by Shardhakoul** [comment]
Checked and Approved.
