### ISSUE TITLE
Activity Diagram for Circle Epic

### ISSUE THREAD

**Issue by EashanKaushik** [gcivil-nyu-org/S2022-Team-6-repo#7]
As a developer, I want to visualize the activity diagram on the Wiki tab of GitHub.

**Comment by srijanmalhotra2711** [comment]
Please start working on the activity diagram for circles as this will be due on this coming wednesday.

**Comment by chinmaykulkarni95** [comment]
The activity diagram for the circle epic has been completed and uploaded on the wiki.

**Comment by srijanmalhotra2711** [comment]
Checked and Approved.
